### ISSUE TITLE
README-*cc-options should go

### ISSUE THREAD

**Issue by punund** [thomas-maeder/popeye#201]
These files:
* [README-gcc-options](https://github.com/thomas-maeder/popeye/tree/master/toolchains/gcc/README-gcc-options)
* [README-icc-options](https://github.com/thomas-maeder/popeye/tree/master/toolchains/icc/README-icc-options)
* [README-cc-options](https://github.com/thomas-maeder/popeye/tree/master/toolchains/Sun-cc/README-cc-options)

should not be here for various reasons:

* they are not part of popeye
* they are many years old and are not useful in any way (anyone uses Sun compiler now?)
* they are HUGE! :elephant: (500K for gcc options)
* README-gcc-options conains "invariant section" wording referring to GNU Free Documentation License, which makes Debian/Ubuntu packaging tools unhappy

**Comment by thomas-maeder** [comment]
deleted all README files under toolchains
