### ISSUE TITLE
fprintf raises error with "hardening" flags

### ISSUE THREAD

**Issue by punund** [thomas-maeder/popeye#202]
This should probably use `fputs`:

https://github.com/thomas-maeder/popeye/blob/master/output/latex/goal_writer.c#L85

Option `-Werror=format-security` is added by Debian/Ubuntu build tools by default.  We could work around this, but this `fprintf` clearly is mispaced, as there are only two arguments.

**Comment by thomas-maeder** [comment]
Fixed for 4.75
