### ISSUE TITLE
licensing contradictions

### ISSUE THREAD

**Issue by punund** [thomas-maeder/popeye#204]
The `py-engl.txt` states:

    The only restriction that we impose is that Popeye be distributed in its entirety.

However, the presence of file `COPYING` implies that popeye is distributed under the terms of GPLv2, which doesn't impose this restriction, and imposes various others.

It may be worthwhie to clear this contradiction, as well as to include file `LICENSE` explicitely containing the right license.

**Comment by thomas-maeder** [comment]
Removed COPIER COPYING KOPIEREN again. They had been imposed by SourceForge.
