### ISSUE TITLE
Missing error message

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#207]
Sometimes Popeye does not report input errors correctly:
Anfang
Forderung H#2
Steine Weiss Ka2 Xb1 Schwarz Ke8 Df8
Ende
Xb1 is invalid, but Popeye only reacts with "Es fehlt ein weisser oder schwarzer Koenig". If you use Noboard option the cause is not obvious, Without Noboard the board only contains Ka2, so you may deduce that something after Ka2 was not ok.
I would expect: Stoerende eingabe: Xb1
Likewise, if the second or subsequent option is misspelled, solution is aborted with "Es fehlt ..." - without any clues. However, if the first option is misspelled, we get excellent help: "Eingabe-Fehler:Option nicht erkannt - Einlesen von Optionen beendet. Stoerende Eingabe: ..."
Likewise with the second condition or subsequent condition
small issue, usually not a problem

**Comment by thomas-maeder** [comment]
Added for 4.77
