### ISSUE TITLE
Circe Assassin + Ser-a=b

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#209]
Maybe I am missing something, but this I do not understand
1) X=>Y
bem part 1 / bed circe assassin / steine / weiss Ka4 Da7 Th5 / schwarz Kg6 Ba5
forderung Ser-a=>b1 / steine / weiss Ka4 Ta5 / schwarz Kg6 Ba7 / ende
correctly solves to 1.Th5a5[+sBa7] a=>b
2) Y=>Z
bem part 2 / bed circe assassin / steine / weiss Ka4 Ta5 / schwarz Kg6 Ba7
forderung Ser-a=>b1 / steine / weiss Ka4 / schwarz Kg6 Ba7 / ende
correctly solves to 1.Ta5a7[+sBa7] a=>b
3) X=>Z
So why does the combined problem not solve:
bem part 1+2 / bed circe assassin / steine / weiss Ka4 Da7 Th5 / schwarz Kg6 Ba5
forderung Ser-a=>b2 / steine / weiss Ka4 / schwarz Kg6 Ba7 / ende
Popeye 4.73 says no solution, expected was
1.Th5a5[+sBa7] 2. Ta5a7[+sBa7] a=>b

**Comment by thomas-maeder** [comment]
Fixed for 4.75
