### ISSUE TITLE
blank refutation?

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#210]
anfang / ford S#6 / bed  schwarzschaecher / option verf 
steine / weiss Kf3 Ld8 / schwarz Kh1 Sd1 Sd6 Bc2 Be7 / ende
With the parameters above I get strange refutations like 
 1.Ld8-b6 ?  Aber  1... !

**Comment by thomas-maeder** [comment]
The refutation correct.
In schwarzschaecher, Black does a null move if he can't deliver check.
In this case, the null move is the refutation.
