### ISSUE TITLE
Small documentation issues

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#211]
Going through the documentation in German, English and French for Popeye when constructing Teddy, I stumbled upon some minor errors / differences between the three files. Only details, low priority!

**In py-deut.txt**
1) Information about Anticire + Cheylan/Calvet missing in the Nach ... part 
(but mentioned later)
2) Information about Circe, Immunschach, PhantomSchach and GenferSchach + RexInklusive missing in the Nach ... part (but mentioned later)
3) Condition Spiegelcirce missing
4) Condition Supercirce missing
5) misspelling: Republikanerscahch
6) Orthogonal missing in Gridchess example
7) Andernach Grasshopper is still there

**In py-engl.txt**
1) Information about Circe, Immunchess, Phantomchess and Genevachess + RexInklusive missing in the After ... part  (but mentioned later)
2) Andernach Grasshopper is still there
3) about MVS, Atari ... eventually -> maybe (or possibly). Eventually means "in the end".

**In py-fran.txt**
1) Condition Circemalefique missing
2) Condition Supercirce missing
3) Andernach Grasshopper is still there
4) Information about Defense + number missing
5) Information about SEMI together with Reflex-condition is missing
6) misspelling piece: pos\'eidon

**General:**
1) The order of conditions and statements about them is not quite the same in the three files (98% ok)
2) References to sourceforge should be updated

**Comment by thomas-maeder** [comment]
py-deut.txt:
1) not found
2) not found
3/4) fixed (removed them in the other py-*.txt as well)
5/6/7) fixed

py-engl.txt:
1) not found
2) fixed
3) removed section altogether

py-frant.xt:
1/2) fixed (removed them in the other py-*.txt as well)
3/4) fixed
5) not found
6) not found

General
1) too much work :-)
2) fixed

Can you please elaborate on the items where I put "not found"?

**Comment by BjornEnemark** [comment]
py-deut.txt
1) in py-fran.txt there is a statement (lines 274-276 in 4.75)
	Pour toutes les conditions AntiCirce, on peut indiquer s'il s'agit du type Cheylan ou Calvet. 
        Si rien n'est indique, le type utilise est Calvet.
this information is not in py-deut.txt, lines 277-302
2) in py-fran.txt, lines 271-272

**Comment by BjornEnemark** [comment]
(continued)
	Apres quelques conditions Circe, Immun, Madrasi, EchecsPhantom
	ou EchecsGeneve, on peut entrer le mot-cle "RexInclusif".
not in py-deut.txt, lines 277-302

**py-engl.txt**
1) as py-deut.txt, 2)

**py-fran.txt**
5) in py-deut, line 631 in 4.75 it says
	SEMI wirkt natuerlich nur im Zusammenhang mit Reflexforderungen.
the corresponding warning is not after line 630 in py-fran.txt

6) line 1018 says
	po      pos\'eidon

All very small issues, found while making Teddy and thus working through the three documentation files.

**Comment by thomas-maeder** [comment]
> py-deut.txt
> 1) in py-fran.txt there is a statement (lines 274-276 in 4.75)
> Pour toutes les conditions AntiCirce, on peut indiquer s'il s'agit du type Cheylan ou Calvet.
> Si rien n'est indique, le type utilise est Calvet.

> this information is not in py-deut.txt, lines 277-302

> 2) in py-fran.txt, lines 271-272

Removed from py-fran.txt and py-engl.txt; Cheylan, Calvet and their default are documented elsewhere.

**Comment by thomas-maeder** [comment]
> py-fran.txt
> 5) in py-deut, line 631 in 4.75 it says
> SEMI wirkt natuerlich nur im Zusammenhang mit Reflexforderungen.
> the corresponding warning is not after line 630 in py-fran.txt

Fixed.

**Comment by thomas-maeder** [comment]
> 6) line 1018 says
> po pos\'eidon

Fixed.
