### ISSUE TITLE
confusion between "Circe Einstein" and "Circe" + "EinsteinChess"

### ISSUE THREAD

**Issue by Geoff-Foster** [thomas-maeder/popeye#212]
When solving a problem with conditions EinsteinChess and Circe, the following input is sometimes used:

condition Circe Einstein

However, this now means Circe with the captured piece transformed in Einstein sequence, which might not be what the solver meant! There needs to be some way of differentiating between "Circe Einstein" and "Circe" + "Einstein". There are several workarounds, such as specifying "Einstein" before "Circe", or using the full name "EinsteinChess". However untrained users are not aware of what is happening, so Popeye gives unexpected results. Maybe a delimiter (such as "\") could be used between options? For example:

condition Circe \ Einstein

**Comment by thomas-maeder** [comment]
There is no easy solution to this problem short of a new input language that allows grouping input words in a more structured way.

Untrained user are better of using a GUI interface like Olive.
