### ISSUE TITLE
castling in norsk sjakk

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#214]
PY does not change rook -> bishop as part of castling

**Comment by thomas-maeder** [comment]
Hi Bjørn

Popeye has done castling like this "forever" (i.e. since at least 4.37).

Are you sure that what you describe is the correct behaviour?

**Comment by BjornEnemark** [comment]
I do not have any text that describes castling in Norsk Sjakk. But I have - from the inventor of the condition, N.A. Bakke - received a problem that uses this change

**Comment by thomas-maeder** [comment]
Is it a published problem that we could quote in the EXAMPLES?

**Comment by BjornEnemark** [comment]
Hi Thomas,

The problem is to be published in Problemskak in the July issue (July 1st)

Nils Adrian Bakke
Problemskak 2017-July

S#5    Norsk sjakk                         3+4
            Maximummer

1. Kc5   Th1L   2. Kd6  La8T
3. Dh5S  Ta1L   4. e4   Lh8T
5. e5    0-0f8L#

kind regards
Bjørn


Den 2017-05-21 kl. 07:33 skrev Thomas Maeder:

**Comment by thomas-maeder** [comment]
Fixed for 4.77
