### ISSUE TITLE
Double maximummer is broken

### ISSUE THREAD

**Issue by dturevski** [thomas-maeder/popeye#217]
```
BeginProblem
Stipulation #1
Option Variation NoBoard
Condition Maximummer WhiteMaximummer
Pieces
  white  Pg6 Kh6 Ba2
  black  Kh8
EndProblem
```

---

Expected: no solution (the only legal move is Ba2-g8)
Actual: 

```
Popeye Windows-64Bit v4.75 (128 MB)
   1.g6-g7 # !
solution finished. Time = 0.016 s

```

**Comment by adrianstori** [comment]
Works OK if specifying
   Condition BlackMaximummer WhiteMaximummer
(see also Stipulation ~1)

**Comment by dturevski** [comment]
That doesn't fix the problem at all, it only introduces a new one that needs fixing: why there are two conditions - Maximummer and BlackMaximummer that mean the same thing?

I know about the stipulation ~1, thank you very much. If you take a look at my gui for popeye
- http://www.yacpdb.org/#static/olive - you may find shortcut buttons for "~1" and "~1 halfduplex" on the toolbar intended to list all legal black/white moves.

**Comment by adrianstori** [comment]
Just wanted to add some info, I've also encountered this problem...  Popeye seems to handle w&b max. fine, it seems to be just an issue with recognizing the stipulation.

**Comment by thomas-maeder** [comment]
This bug has literally existed "forever" (at least since v4.37).

Somehow, the indication of Maximummer cancels out WhiteMaximummer. If only White Maximmumer is specified, Popeye only tries 1.Bg8.

**Comment by thomas-maeder** [comment]
Resolution: This is not a bug in the solving behaviour, but there is potential in the documentation, and maybe for a warning.

Maximummer and (Black|White)Maximummer don't mix. [NB: same for *Ultraschachzwang]

Maximummer means that the defending side is restricted, *and that the other side isn't*. I.e. in the duplex part of a duplex s# problem, White is restricted - and Black isn't.

**Comment by thomas-maeder** [comment]
- enhanced docs
- produce an error message
