### ISSUE TITLE
MaxTime problem

### ISSUE THREAD

**Issue by viktoras-pal** [thomas-maeder/popeye#218]
The option MaxTime does not work with some of the helpmates. Example:

BeginProblem
Stipulation h#6
Option  MaxTime 10
Pieces
  white  Qd1 Pf3a2 Ke1
  black  Bf1g1 Kh1 Qc1 Pb3c3e3g3b2e2g2h2 Sd2a1 Rc2b1
EndProblem

Popeye don't stop calculating.

**Comment by thomas-maeder** [comment]
This bug was introduced in v4.75

**Comment by thomas-maeder** [comment]
Fixed for 4.77
