### ISSUE TITLE
Black Transmuting king with lions not making all expected moves

### ISSUE THREAD

**Issue by Ruziklan** [thomas-maeder/popeye#220]
Zielfeld g5 in the following example is reached correctly after 1.b8R+ and 1.b8Q+
=========================================
Stipulation rZg51
Condition blacktransmut
Pieces
White RLa8 Ka7 Pb7 Pg5
Black Kg8
=========================================
Popeye Windows-32Bit v4.75 (4096 KB)

   1.b7-b8=Q + !
      1...Kg8*g5 z

   1.b7-b8=R + !
      1...Kg8*g5 z

solution finished. Time = 0.078 s
=========================================

But e6 is not reached at all, although 1.b8Q+ is expected to solve:
=========================================
Stipulation rZe61
Condition blacktransmut
Protocol C:\Documents and Settings\NOTEBOOK3\Desktop\Neskodne\Popeye\py.txt
Pieces
White RLa8 Ka7 Pb7 Pg5
Black Kg8
=========================================
Popeye Windows-32Bit v4.75 (4096 KB)

solution finished. Time = 0.078 s
=========================================

Using condition TransmutedKings for both sides helps. So only one-sided transmutation seems to be wrong.
=========================================
Stipulation rZe61
Condition TransmutedKings
Pieces
White RLa8 Ka7 Pb7 Pg5
Black Kg8
=========================================
Popeye Windows-32Bit v4.75 (4096 KB)

   1.b7-b8=Q + !
      1...Kg8-e6 z

solution finished. Time = 0.093 s
=========================================

**Comment by thomas-maeder** [comment]
Fixed for 4.77
