### ISSUE TITLE
Reproducible bug in INTE for helpmates, in Popeye 4.75

### ISSUE THREAD

**Issue by andrew-buchanan** [thomas-maeder/popeye#222]
There seems to be an interesting bug in the INTE function of Popeye 4.75. I have not checked in earlier versions:

begi
prot outputp.txt
fors r3k2r/1p4p1/5p2/7q/7p/1p4pp/5s2/3bK2R
stip h#4.0
opti inte noca h1
next
fors r3k2r/1p4p1/5p2/7q/7p/1p4pp/5s2/3bK2R
stip h#4.0
opti noca h1
end

Normally, one would expect these to deliver the same result, yes? Well they don't.

we get output for the two cases:
  1.0-0-0 Rh1xh3  2.Kc8-b8 Rh3xh4  3.Kb8-a8 Rh4xh5  4.Rd8-b8 Rh5-a5  
and
  1.g3-g2 Ke1xf2  2.0-0 Rh1xd1  3.Kg8-h8 Rd1-d5  4.Rf8-g8 Rd5xh5 #
  1.0-0-0 Rh1xh3  2.Kc8-b8 Rh3xh4  3.Kb8-a8 Rh4xh5  4.Rd8-b8 Rh5-a5 #

Please can you fix this as soon as convenient.

As a user, keen to know how widespread is the impact of this bug? What retesting of existing material may be required, please?

Thanks for your time!

[edit: github forum doesn't seem to like asterisks, so character is replaced by x]

**Comment by andrew-buchanan** [comment]
Detailed evidence:
[inputp - BUG.txt](https://github.com/thomas-maeder/popeye/files/852334/inputp.-.BUG.txt)
[outputp - BUG.txt](https://github.com/thomas-maeder/popeye/files/852335/outputp.-.BUG.txt)

**Comment by thomas-maeder** [comment]
The minimal example is:

begin
pieces white kf2 rh1 black ke8 qh5 ra8h8 bd1 pb3b7f6g7g2h3h4
stipulation h#3
option intelligent nocastling h1
end

Intelligent mode doesn't find the solution if the (irrelevant) nocastling option is set.

I don't think that the usage of option nocastling is very widespread.

**Comment by thomas-maeder** [comment]
Fixed for 4.77
