### ISSUE TITLE
Strange behavior with SuperGuards

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#225]
In Popeye 4.77 this problem...

beginproblem
condition superguards
forsyth 2b1k3/p7/8/8/8/1S6/8/4K3
stip h%1
endproblem

returns the solution
  1.a7-a5 Sb3*a5 %
which is fine, but this problem...

beginproblem
condition superguards
forsyth 4k3/pp6/8/8/8/1S6/8/4K3
stip h%1
endproblem

doesn't return any solution. Why doesn't the above solution work here too? The only explanation I have is that the black b-pawn is observing the black a-pawn "en passant" but this seems pretty far-fetched. Is this an intended SuperGuards behavior or a bug?

**Comment by thomas-maeder** [comment]
4.63 (the release where superguards were introduced) solved the second example just like the first. Since 4.65, Popeye doesn't find that solution any more.

**Comment by thomas-maeder** [comment]
Fixed for 4.79
