### ISSUE TITLE
Pawns on 1st rank in ReversalEinsteinChess and AntiEinsteinChess

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#227]
In EinsteinChess, white pawns on the 1st rank have up to 5 possible moves: a single, double, or triple jump, and up to two diagonal captures. This can be verified in Popeye:

```
begin
cond EinsteinChess
forsyth 4k3/8/8/8/8/8/1r1r4/2P4K
stip h~0.5
end
```
```
  1...c1-c4
  1...c1-c3
  1...c1-c2
  1...c1*d2=S
  1...c1*b2=S
  1...Kh1-g1
```
But when I replace EinsteinChess with ReversalEinsteinChess or AntiEinsteinChess, then Popeye 4.77 omits the pawn moves and only the king move remains. This contradicts online descriptions of these conditions, e.g.

http://kobulchess.com/en/problems/chess-originals-2014/464-janos-mikitovics-fairy.html
http://phenix-echecs.fr/definitions.php

**Comment by thomas-maeder** [comment]
Fixed for 4.79
