### ISSUE TITLE
sstip mate with/out capture: mate is shown as check

### ISSUE THREAD

**Issue by Laborczi** [thomas-maeder/popeye#228]
If a structured stipulation prescribes mate with or without capture, then the solution is given both as check and mate. Example Popeye input:
> beginproblem
> pieces white Kh6 Qb1 black Kh8 Ph7
> sstip white 1a[!x&#]d
> remark #1 without capture
> endproblem

The solution written by Popeye:
> 1.Qb1-b8 + !
> 1.Qb1-b8 # !

Only the second line is correct.

**Comment by thomas-maeder** [comment]
Fixed for 4.81
