### ISSUE TITLE
 KoeKo+MessignyChess segfaults pywin64.exe (4.67 and newer)

### ISSUE THREAD

**Issue by dturevski** [thomas-maeder/popeye#236]
`BeginProblem
Stipulation #1
Option NoBoard
Condition KoeKo MessignyChess
Pieces
  black  Ke8
  white  Ke1
EndProblem

Popeye Windows-64Bit v4.79 (1024 MB)
Segmentation fault`

**Comment by thomas-maeder** [comment]
Hmm. Not on the Windows I use for testing.

**Comment by dturevski** [comment]
Can reproduce on Win10 Pro & Win10 Home.
The "Segmentation fault" is only displayed when run from MinGW+bash
When run from the plain cmd.exe it dies quietly, but without printing "Solution finished. Time = ..."
Probably, because cmd.exe unlike bash ignores the non-zero exit codes.
Can not reproduce in Linux.

**Comment by thomas-maeder** [comment]
I have tried to reproduce this once more on both Windows 10 and Windows 11 without "success".
