### ISSUE TITLE
MagicSquares + RexInclusive

### ISSUE THREAD

**Issue by adrianstori** [thomas-maeder/popeye#238]
Is there a way to make a king / royal piece *also* change colour when moving onto a magic square?  I tried specifying combinations of "white magic Ka1" and "MagicSquares a2 type1 | type2" without success.

If currently not possible, adding such a feature will be welcome (*any* piece moving onto a magic square changes colour).  I understand there may not be a large 'market' for this feature, but it would provide a more complete solution similar to other RexInclusive coverage instances.

(My problem in fact uses a magic board -- 64 magic squares --, where any piece *landing* -- moving or reborn -- onto a magic square changes colour:  i.e., circe rebirths are also of the other colour -- but this can be accomplished with circe turncoats anyway.)

**Comment by thomas-maeder** [comment]
Yes, I think that there is a way.

There is the general assumption that the side to be checked has a king in stipulations that end in something related to check (including mate). But that assumption already isn't met in Royal Dynasty.

Could you provide an example problem, preferably simpler than something with 64 magic squares? :- )

**Comment by adrianstori** [comment]
Right now all I have is P1298971 (there is a more detailed solution in yacpdb http://www.yacpdb.org/#305789), which is definitely not an ideal testcase.  I'll try to find time to concoct something simpler...

**Comment by adrianstori** [comment]
Perhaps this might do:

pieces
black Kc1
stipulation hZa1 1
condition magicsquares rexinclusiv a1b1

1.Kc1-b1=w Kb1-a1=b z

**Comment by thomas-maeder** [comment]
The author's solution of P1298971 doesn't work.
5. Kxa5=w[+wTa1=s]+ and 5. Kxb5=w[+wLf1=s]+ are not ??, but legal cross-checks.

**Comment by thomas-maeder** [comment]
Also, the rules are not clear: what happens if both sides have a king and the white king moves to a magic square?

In Royal Dynasty, no side would have royal piece until one of the Black kings moves to a magic square. Is that the intention for Magic Squares Rex inclusive?

**Comment by adrianstori** [comment]
"The author's solution of P1298971 doesn't work.  5. Kxa5=w[+wTa1=s]+ and 5. Kxb5=w[+wLf1=s]+ are not ??, but legal cross-checks."

Cross-checks indeed (and beautiful ones too!), but this particular problem is Ohneschach, hence these moves *here* are illegal.

"Also, the rules are not clear: what happens if both sides have a king and the white king moves to a magic square?"

I don't claim authorship of the idea, just believe it's nice to complete/fill a visible 'hole' in the magic-squares scheme of things.  I'd follow, in coding, the path of least resistance...  :-)

**Comment by thomas-maeder** [comment]
Sorry for the wait ...
Well, with Ohneschach, all bets are off. Ohneschach's definition is an inherently unsound, and meaningful results with Ohneschach (both on the board an the computer) are merely a result of luck.
