### ISSUE TITLE
Solution not found after twinning

### ISSUE THREAD

**Issue by vlaicu** [thomas-maeder/popeye#239]
In a problem using a chameleon sequence, Popeye fails to find the solution in the twin.

From the output it seems Popeye simply "forgets" to apply the chameleon sequence to the pieces.
This is not a new bug specific to version 4.81 - it appears as well in version 4.79.

**Comment by thomas-maeder** [comment]
Hi Vlaicu
Could you please post a simple example problem?

**Comment by vlaicu** [comment]
BeginProblem
Pieces
White chameleon VAg2
Black chameleon PAf1
White Sf6 Kh1
Black Ba8 Kh8 Pd6 Pe5 Sb3 Ph2 Ba1
Stipulation h#2
Condition ChameleonSequence PA VA PA
Option Variation NoBoard
Twin Move f6 h5
EndProblem

Popeye fails to find the following solution in the twin:
1.cPAf1-f7=cVA Kh1*h2   2.cVAf7-g8=cPA cVAg2-h3=cPA #

The reason for this failure is that the chameleon sequence is no longer applied in the twin:
 37  (cPAf1-f7    Time = 0.135 s)

**Comment by thomas-maeder** [comment]
Fixed for 4.83
