### ISSUE TITLE
Bug in WhiteMustCapture Ultra

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#240]
Here are two artificial problems failing with 4.81:

```
begin
forsyth r3k2r/4q1b1/5Q2/8/8/8/8/3K4
stip hze8 1.5
cond WhiteMustCapture Ultra
end

  1...Qf6*e7   2.Bg7-a1 Qe7*e8 z
[...]
```
This solution is not legal. 1...Qf6*e7 should be check, but Popeye doesn't mark it as check, Black ignores the check, and then White goes ahead and captures the king on e8! I expect no solution.

```
begin
forsyth 4k3/8/bs6/8/P7/8/4B3/R3K2R
stip h#1
cond BlackMustCapture Ultra
end

  1.Ba6*e2 Rh1-h8 #
  1.Sb6*a4 + Be2-h5 #
```
Popeye marks 1.Sb6*a4 as check, but it is not check. Popeye is missing the 3rd solution

1.Sb6*a4 Rh1-h8 #

**Comment by thomas-maeder** [comment]
Luckily, the problem only existed in positions where castling is possible.

Fixed for 4.83
