### ISSUE TITLE
limited retractor capability

### ISSUE THREAD

**Issue by andrew-buchanan** [thomas-maeder/popeye#242]
My number 1 wish for Popeye is to be able to retract moves, please. There are nearly 2,000 help retractors in Popeye right now. The way to make this task tractable in Popeye is to make NO attempt to verify the legality of retracted position (beyond impossible checks). It can be left to a human to check retro considerations. In many cases (e.g. Edith Baird's 150 problems) there is no retro content anyway. Need stipulation syntax that allows for e.g. "-1(w+s), dann h#1" or "-1w, dann h#1.5" or "-1(w+s), dann hs#1,5" (three random examples by Baird).
Thanks for all your work.

**Comment by andrew-buchanan** [comment]
Just wanted to bump this to ask what's the thinking please. Not looking for any consideration of *position* legality. Just looking to undo whatever legal move might have just happened. Thanks so much for all your work.

**Comment by auxbuss** [comment]
Just +1 to this.

Looking to solve a Baird problem, I just tried `stipulation -1->h#2`, which caused a segmentation fault. I didn't expect it to work – just hopeful – so it would be nice to have this ability.

**Comment by andrew-buchanan** [comment]
Since then, a new engine, deadpos, has appeared which has been used to prove or cook about 80 help-retractors in PDB, including 19 of Baird's. See https://pdb.dieschwalbe.de/overview.jsp?expression=k%3D%27help+ret%27+and+cpluscomment%3D%27deadpos%27. There's about 50 new help-retractors not published in PDB, that were tested at creation by deadpos. See „2 Steps Down, 2 Steps Up“ feenschach: f-259 (Nov-Dec 2024),  pp.179-188 (in English) & https://drive.google.com/file/d/1p51auxi0xgXDdZG2UrRqIfMD1FUyBJ9x/view?pli=1

This is deadpos, https://github.com/miguel-ambrona/deadpos. As the name suggests, it was originally written to solve problems that involve the Dead Position rule, but since limited retraction is often necessary for the solution of these, it made sense to have broader capabilities to handle help-retractors. Miguel is now at work on a more general retro engine called Sherlock.
