### ISSUE TITLE
MirrorCirce not applied to kamikaze pieces

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#246]
This "Kamikaze MirrorCirce" problem was working in 4.55, but in 4.63 onwards the "Mirror" option is only applied to the captured piece and no longer applied to the *capturing* piece, giving wrong solutions.

```
begin
origin P1299017
pieces white Kb3 black Kd1 neutral kamikaze Pc2d2e7f7
stip h#2
cond MirrorCirce
end
```

**Comment by thomas-maeder** [comment]
Fixed for 4.83
