### ISSUE TITLE
Fix any-move aim (~) in long sstipulation

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#251]
The any-move aim works in structured stipulations of length 1 and 2

```
begin
pieces white Pa3 black Ph6
sstip white 1:1h[~]h
next
pieces white Pa3 black Ph6
sstip white 2:2hh[~]
end
```
but fails for longer sstipulations (Popeye returns no solutions).

```
begin
pieces white Pa3 black Ph6
sstip white 3:3h[~]h
next
pieces white Pa3 black Ph6
sstip white 4:4hh[~]
end
```

As a workaround, I use the "mate or not mate" trick

```
begin
pieces white Pa3 black Ph6
sstip white 3:3h[#|!#]h
next
pieces white Pa3 black Ph6
sstip white 4:4hh[#|!#]
end
```

but this doesn't work with LosingChess ("LosingChess incompatible with check or mate stipulations"), and it outputs illegal games with ChecklessChess because of issue 247 which is not worth fixing.

```
begin
pieces white Pb5 black Ka8
sstip black 2:2hh[~]
cond ChecklessChess
next
pieces white Pb5 black Ka8
sstip black 2:2hh[#|!#]
cond ChecklessChess
end
```

**Comment by thomas-maeder** [comment]
The reason for the current behavior is that
* the stipulation asks for an exact number of moves
* the goal is reached in a lower number of moves, i.e. too early

The equivalent of
sstip white 3:3h[~]h
in traditional stipulations id
stip exact-h~1.5
, for which Popeye doesn't print a solution either. So we are not dealing with a sstip bug here, but with an unexpected behaviour of goal ~.

After all, we get the solution
  1.a3-a4
if we ask for a non-exact number of moves, either with
stip h~1.5
or
sstip 3:1h[~]h

I tend to think that the current behaviour is correct; after all, it could be Black's defensive tactic to force White to, say, capture too early in an exact-x2 stipulation.

**Comment by thomas-maeder** [comment]
That said, I obviously see that printing all legal move sequences may be useful in some cases.

Further thinking is required to resolve this issue.

**Comment by flab03** [comment]
I see. But how come with the not-mate aim (!#), the game goes on even if the same side is not-mate early? Maybe you could generalize this behavior and allow the not-not-any aim (!!~) as a way to print all legal moves sequences?

By the way, how can we use the auto-mate aim (!#) in sstipulation? It has the same notation as not-mate. The documentation says that it should be possible:

> "structured form" [...] allows all stipulations to be indicated that can also be indicated in traditional form using the command "stipulation".

**Comment by thomas-maeder** [comment]
>2 years later, and I have finally thought further. This works:

begin
pieces white Pa3 black Ph6
sstip white 2:2hh[1h[~]h]
cond ChecklessChess

next

pieces white Pa3 black Ph6
sstip white 2:2hh[2hh[~]]
cond ChecklessChess
end
