### ISSUE TITLE
Castling in PointReflection

### ISSUE THREAD

**Issue by EricHuber** [thomas-maeder/popeye#253]
According to the definition of PointReflection provided in the [announcement of the Sake tourney 2019](http://www.sachmatija.puslapiai.lt/wccc2019/wp-content/uploads/2019/07/19th-Japanese-Sake-Tourney.pdf):
 **Only non-reflected K and R can castle**

**Bug:** With Popeye 4.83, K and R can castle when they are reflected.

Could you solve this issue?
I think that the intention of the inventor of the fairy condition was that King and Rook cannot castle when they are reflected by another piece (King not reflected by King, Rook not reflected by Rook).

**Example with white King e1 and white Rook h1 reflected by different black units on d8 and a8** (it works with any kind of unit on d8 and a8) :

> BeginProblem
> Pieces
> White Ke1 Rh1
> Black Ka8 Rd8
> Stipulation ~1
> Condition pointreflection
> Option MoveNumbers NoBoard
> EndProblem

Popeye result:
 
>  1  (0-0    Time = 0.017 s)
>    1.0-0 !
>   2  (Ke1-a1    Time = 0.019 s)
>   3  (Ke1-b1    Time = 0.021 s)
>    1.Ke1-b1 !
>   4  (Ke1-c1    Time = 0.022 s)
>    1.Ke1-c1 !
>   5  (Ke1-d1    Time = 0.022 s)
>   6  (Ke1-e8    Time = 0.023 s)
>   7  (Ke1-e7    Time = 0.024 s)
>    1.Ke1-e7 !
>   8  (Ke1-e6    Time = 0.024 s)
>    1.Ke1-e6 !
>   9  (Ke1-e5    Time = 0.025 s)
>    1.Ke1-e5 !
>  10  (Ke1-e4    Time = 0.027 s)
>    1.Ke1-e4 !
>  11  (Ke1-e3    Time = 0.028 s)
>    1.Ke1-e3 !
>  12  (Ke1-e2    Time = 0.029 s)
>    1.Ke1-e2 !
>  13  (Ke1-g1    Time = 0.031 s)
>    1.Ke1-g1 !
>  14  (Ke1-f1    Time = 0.033 s)
>    1.Ke1-f1 !
>  15  (Rh1-g2    Time = 0.044 s)
>    1.Rh1-g2 !
>  16  (Rh1-g1    Time = 0.049 s)
>    1.Rh1-g1 !
>  17  (Rh1-h2    Time = 0.055 s)
>    1.Rh1-h2 !
> solution finished. Time = 0.056 s

**Comment by thomas-maeder** [comment]
fixed for 4.87
