### ISSUE TITLE
Missing PG solution in FaceToFace

### ISSUE THREAD

**Issue by flab03** [thomas-maeder/popeye#256]
Popeye (all versions) fails to find the solution to this PG taken from Christian Poisson's PDF book "562 Parties Justificatives Homebase":

```
begin
origin CPoisson-226
stip dia 3.5
forsyth rsbqkb1r/pppppppp/8/8/8/8/PPP1PPPP/RSBQKBSR
cond FaceToFace
end

Author's solution:
1.d2-d3 Sg8-h6 2.Bc1*h6 h7*d3 3.Bh6-d2 d3-h7 4.Bd2-c1

```

I think there's a problem only when solving PGs.

**Comment by thomas-maeder** [comment]
Fixed for 4.85
