### ISSUE TITLE
Option Intelligent cannot find H#1 - fairy chess not involved 

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#257]
Anfang
Forderung H#1
Option  Intelligent Varianten 
Steine
Weiss    Ke5 Dh8 Th3 Lf1 Bg3 Bh5 
Schwarz  Kf3 Sf4 Be3 Bf2 
Ende
This simple helpmate in one cannot be solved by Popeye 4.83!
Ok if option intelligent is removed:  1.Sf4*h5 Dh8*h5 #

**Comment by thomas-maeder** [comment]
Fixed for 4.85
