### ISSUE TITLE
Solution with en passant capture not found in intelligent mode

### ISSUE THREAD

**Issue by viktoras-pal** [thomas-maeder/popeye#258]
BeginProblem
Stipulation h#3
Option NoBoard Intelligent
Pieces
  black  Kf2 Rc3b3 Se4 Pc7
  white  Pe5d5a7 Bg8b8 Rd8 Kc8
EndProblem

**Comment by thomas-maeder** [comment]
Popeye was confused by the check on the c line intercepted by the pawn capturing en passant.
Fixed for 4.85
