### ISSUE TITLE
Incorrect (or perhaps redundant) condition

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#264]
Line 1144 of `pieces/attributes/total_invisible/capture_by_invisible.c` is:
```c
  else if ((motivation[id].last.acts_when==nbply || motivation[id].last.acts_when==nbply)
```
This looks wrong, as both conditions are identical.  I'm guessing that the second condition should be something different, though I suppose it's possible that it's just redundant and can be removed.

**Comment by thomas-maeder** [comment]
Fixed
