### ISSUE TITLE
Duplicate branch

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#265]
[GCC](https://gcc.gnu.org/) points out that lines 1833-1842 and 1846-1855 in `pieces/attributes/total_invisible/decisions.c` have identical behavior, hence the branch on lines 1830-1831 is irrelevant.  This isn't _obviously_ a bug to me, but it's probably worth a closer look by someone who understands this logic.  Perhaps lines 1836-1839 and/or 1849-1852 need to be filled in with actual code.

**Comment by thomas-maeder** [comment]
Hi Joshua
This is my first reaction to your many contributions; so: thank you!

GCC ignores the comments, which I think are useful in this particular case. So I am reluctant to remove this one.

BTW: What command line options are you using? I don't get a warning from gcc with the options that I am usually using.

**Comment by JoshuaGreen** [comment]
Thanks for looking.  The comments were why I felt it was unlikely that this was a legitimate bug, and I absolutely trust your judgment here.

I tend to enable an _absurd_ number of warnings and then, based on the results, decide how much work I'm willing to do.  I guess I used `gcc-9` here with the flags

```-Wpedantic -pedantic-errors -Wall -Wextra -Walloc-zero -Walloca -Warray-bounds=2 -Wcast-qual -Wcast-align=strict -Wconversion -Wduplicated-branches -Wduplicated-cond -Wfloat-equal -Wformat=2 -Wformat-overflow=2 -Wformat-signedness -Wformat-truncation=2 -Winvalid-pch -Wlogical-op -Wmissing-declarations -Wnull-dereference -Wredundant-decls -Wshadow -Wshift-negative-value -Wshift-overflow=3 -Wstrict-overflow -Wstringop-truncation -Wswitch-default -Wswitch-enum -Wsync-nand -Wundef -Wunknown-pragmas -Wunused-macros -Winit-self -Wbad-function-cast -Wwrite-strings -Wjump-misses-init -Wstrict-prototypes -Wold-style-definition -Wmissing-prototypes -Wnested-externs```

(or whichever ones my installed `gcc-9` allowed), but I guess `-Wduplicated-branches` would have been sufficient to raise this particular concern.

**Comment by thomas-maeder** [comment]
I have heavily reduced the number of emitted warnings during the last week, both by fixing code and by not using some of the -W options that don't seem useful.

**Comment by JoshuaGreen** [comment]
For testing I tend to leave all the warnings on, but of course I don't pay much attention to many of them as long as I have other issues to focus on.  For regular builds, I agree that turning off the warnings that are unlikely to point to bugs (and that you have no intention of eliminating) makes sense.

**Comment by JoshuaGreen** [comment]
FWIW, I also agree with closing this ticket. :)
