### ISSUE TITLE
Strange condition(s)

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#274]
In `pieces/attributes/total_invisible/taboo.c`, lines 429-435 are:
```c
if (sq_departure==move_by_invisible
    || sq_departure>=capture_by_invisible)
{
  /* no taboos! */
}
else
{
```
[`cppcheck`](http://cppcheck.sourceforge.net/) observes that `move_by_invisible > capture_by_invisible`, hence the condition on line 429 implies the condition on line 430 and is therefore redundant.  Are these really the correct condition(s) here?

**Comment by thomas-maeder** [comment]
Fixed
