### ISSUE TITLE
Redundancy, or something else?

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#275]
In `stipulation/move_inverter.c`, lines 60-63 are:
```c
if (next_starter!=no_side)
  SLICE_STARTER(si) = (next_starter==no_side
                        ? no_side
                        : advers(next_starter));
```
As [`cppcheck`](http://cppcheck.sourceforge.net/) notes, the condition in the choosery contradicts the condition in the `if` block, hence cannot hold.  The above code is therefore equivalent to
```c
if (next_starter!=no_side)
  SLICE_STARTER(si) = advers(next_starter);
```
but is this the intent?  A plausible alternative is that the `if` shouldn't be there and the block should simply be:
```c
SLICE_STARTER(si) = (next_starter==no_side
                      ? no_side
                      : advers(next_starter));
```
(I can imagine that these are equivalent here, but that isn't obvious to me.)

It's also possible that (at least) one of the two conditions needs to be corrected.

**Comment by thomas-maeder** [comment]
Fixed
