### ISSUE TITLE
close the protocol file

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#281]
It doesn't appear that the protocol file is `fclose`d anywhere.  We should be sure to `fclose` it to ensure that all output is written.  I've added the functionality to `fclose` it; now we just have to decide where/when to do so.  (The end of `main` should work, but maybe there's a more appropriate place.)

**Comment by thomas-maeder** [comment]
protocol_fflush() is called at various places, which should make sure that most of the output is written.

But yes, protocol_close() should probably be invoked.

What if we don't reach the end of the main() function?

**Comment by JoshuaGreen** [comment]
Ideally we'd call `protocol_close` as soon as we're sure no more output would be sent there.  Alas, I don't know the software well enough to know when that is.  Calling at the end of `main` should be "safe," and I suppose we could also call it before calls to `exit`.  Beyond that, I don't really see how to handle other early exits (e.g., `assert` failures), but then that's a general problem with resources (that C++ tries to solve with RAII).

**Comment by JoshuaGreen** [comment]
It looks like the best solution is to register `protocol_close` (and `fxfTeardown` if `defined(FXF)`, I suppose) with [`atexit`](https://en.cppreference.com/w/c/program/atexit).

**Comment by JoshuaGreen** [comment]
I've gone ahead and implemented the [`atexit`](https://en.cppreference.com/w/c/program/atexit) idea in [`develop`](https://github.com/thomas-maeder/popeye/tree/develop).  The freeing functions are NOPs when nothing needs to be done, so this should be harmless.  Time to close this ticket.
