### ISSUE TITLE
Self-check procedure on "make&take + Disparate"

### ISSUE THREAD

**Issue by WalterL-wL** [thomas-maeder/popeye#282]
Employing the combination "make&take + Disparate" PopEye seems to **disregard** "Disparate" on verifying self-check (Selbstschach). When "Disparate" applies and the same kind of stone e.g. the wR moves (first), then the bR mustn't move next (it's like being paralysed for this next one move)! Consequently, the wR should safely enter the sphere of action of the bR without risk of being captured by the bR in the next black move. In this situation neither should the bR give check to the wK in this one next move (in case the move of the wR opened the attacking line)!

This also applies to the situation with two K! Simply spoken, wKa1 and bKa4 whoever makes the first move towards the other K will subsequently mate the other K, because the other K mustn't move. But PopEye will not let the two K enter into contact within 2 fields of each other, obviously due to this faulty self-check procedure by disregarding "Disparate".

THANKS for reviewing!

**Comment by thomas-maeder** [comment]
And astonishingly, Popeye correctly solves the following problem by 1.Kb3-c2 #

begin
pieces white kb3 black kd1  
condition disparate     
stipulation #1
end

**Comment by thomas-maeder** [comment]
Fixed the second part for Popeye 4.85.

@WalterL-wL : please post a minimal problem that illustrates the first part?

**Comment by WalterL-wL** [comment]
THANKS for your efforts! But I'm not sure, if I do understand correctly:

a) my problem occured in the **combination** "m&t + Disparate", so I did not know if "Disparate" on its own worked correctly with two mutually attacking K even already before...
As you write: "Fixed the second part for Popeye 4.85." - so actually WHAT did you fix and WHAT do you mean by "**second part**"? Would it cover the following situation:
(abbreviations are in German=English: T=R, B=P, L=B)

anfa
prot test.txt
bedi **Make&TakeSchach Disparate**
ford #1
Stei Weis Ka2 Td8 Bb6   Schw Ka5 Bb5 Bd5
Opti vari
Ende

   1.Td8-a8 # !
   1.Td8-b8 # !
Problem: PopEye (v 4.83) shows two solutions, but actually there's no one...

Just the move 1. Ka5-b4 and that's it - the Ka2 doesn't protect field b4 (m&t) due to DISPARATE; so there's NO #1...

I attach a protocol file '_prot maeder 130520.txt
[prot maeder 130520.txt](https://github.com/thomas-maeder/popeye/files/4620471/prot.maeder.130520.txt)
_' with comments, "expanding" your presented solution for Disparate (only) '1.Kb3-c2 #' to my original concerns...

b) I'm glad to be able to contribute, but again what do you mean by "please post a minimal problem that illustrates the first part" - WHAT is the first part?
For now I'd assume it's not the **mutual** interaction between two K, but the situation when an attacking line "opens" (so I resend two problems from former e-mails):

anfa
prot test.txt
bedi **Make&TakeSchach Disparate**
ford #1
Stei Weis Ka2 Bd6   Schw Ka5 Ta8 Bb5 Bd5
Opti vari **dupl**
Ende

   ***PopEye presents no solution!!!***
Problem: no solution for w, ok. But for b (see option DUPL) the move 1. Ka5-b4# should mate the wK even in a double way (m&t)...

anfa
prot test.txt
bedi **Make&TakeSchach Disparate**
ford #2
Stei Weis Kh1 Lf3 Sf7   Schw Ka8 Lb7
Opti Vari
Ende

   1.Lf3*b7 # !   ok
   1.Sf7-d6 # !   ?????
Problem: PopEye (v 4.83) presents 2 solutions; the first one is ok, the second one actually doesn't exist:

Ka8 has no escape fields when Sd6 attacks (m&t), and cannot counterattack Sd6 by way of m&t as Sd6 is covered by Lf3 (m&t). Only Lb7 can capture Sd6 (m&t). "**Regularly**", this would be forbidden, as it opens a mate-attack by Lf3 on the bK. BUT here Lf3 (temporarily) is paralysed due to DISPARATE, so it doesn't attack the bK (in the first move)...

... please let me know in case I misinterpreted your request concerning "first part".
THANKS!

**Comment by WalterL-wL** [comment]
SORRY, the "close" was just a (beginner's) mistake...

**Comment by thomas-maeder** [comment]
Your initial text has two paragraphs.

I understood the issue in the second paragraph and fixed it. I named the commit "fixed issue #282", pretending to fix the entire issue - everybody makes beginners' mistakes from time to time :-)

So if you do pieces wka4 bkd1 stipulation #1 condition make&take disparate, you get
1.Ka4-b3# now.

I found the first paragraph more complicated; so I asked you to clarify it.

It seems that I have solved the entire issue. Please have a look at the end of https://github.com/thomas-maeder/popeye/blob/develop/REGRESSIONTESTS/4_83_to_4_85.reg - you can see how Popeye 4.85 will deal with your examples. Does this look right?

**Comment by WalterL-wL** [comment]
Let me call the 4 examples at the end in your link as follows: **REG1,...REG4**

REG1:
**YES**, that's correct now; provided it should also work with Option DUPL the other way around 1. (...) Kd1-c2 #

REG2:
**YES**, that's correct now - NO solution; considering 2 different reasons: 
(1) the b Ka5-b4 can escape both attacks of the w Rd8-a8+ and Rd8-b8+ (issue as discussed); and equally (as a regular m&t issue)
(2) the w Ka2-a3/b3 mustn't attack the b Ka5 due to self-check by the b Pb5, but I take this as given.

AND, provided Option DUPL would show two solutions for black (see REG3):
1. (...) Ka5-a4 # and also 1. (...) Ka5-b4 #

REG3:
**YES**, that's correct now - no solutions for white, 2 solutions for black under Option DUPL (=antipode to REG2); considering the first one 1. (...) Ka5-b4# actually "comprises" 2 different checkmates (by bKb4 and bRa8), but I take this as given. 

REG4:
**YES**, this 1 solution only with #2 (for white) seems correct now. BUT I'm not yet that firm with what kind of "results" of possible moves PopEye will show, so what about (or would it explicitly require a change of stipulation to "=1" ???):
1. Bf3-c6,d5,e4,g2= (paralyses bB, only bK a8-a7/-b8 can move, would be self-checkmate, thus stalemate)

AND as the stipulation is #2, provided by **omitting** wSf7 and applying Option DUPL this would in addition to 1. Bf3*b7# also show a solution for black:
1. (...)   bBb7-c6,d5,e4  (paralyses wBf3) 
2. wKh1-g2 (the only legal w move!)   bB~ x wBf3#

**PERFECT - looks great!!!**
Will you "close" the issue #282 as finished, or would I have to do this?
THANKS a lot!
