### ISSUE TITLE
TotalInvisibles bug in Popeye 4.85

### ISSUE THREAD

**Issue by EricHuber** [thomas-maeder/popeye#290]
BeginProblem
Pieces TotalInvisible 1 White Kb2 Black Ka4 Neutral Rb8
Stipulation h#1
EndProblem

Popeye 4.85 gives no solution.

Popeye 4.83 gives the correct solution:
1.nRb8-b5 pfTI~-~[b4=wR] #
(The invisible is a white piece and can only be wRb3 that moves to b4)

Please correct this bug.

**Comment by thomas-maeder** [comment]
It is not entirely clear whether the combination of neutral pieces and total invisible pieces should be supported, but:

Fixed for 4.87
