### ISSUE TITLE
Stipulation with -> does not find all solutions

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#292]
In the example below (Ser-H#3) Popeye finds all solutions
     Anfang
     Forderung ser-H#3
     Option  Varianten MaxLoesungen 8 
     Steine
     Weiss   Kc2 Sd4
     Schwarz Ka1 Tb3 Sd3
     Ende
  1.Sd3-c1   2.Sc1-a2 Sd4*b3 #
  1.Tb3-a3   2.Sd3-b2   3.Ta3-a2 Sd4-b3 #
  1.Sd3-b2   2.Tb3-a3   3.Ta3-a2 Sd4-b3 #

But if I move the wS and change the stipulation to 1->Ser-H#3 it only finds the short solution
     Anfang
     Forderung 1->ser-H#3
     Option  Varianten MaxLoesungen 8 
     Steine
     Weiss   Kc2 Sb5
     Schwarz Ka1 Tb3 Sd3
     Ende
  1.Sb5-d4   1.Sd3-c1   2.Sc1-a2 Sd4*b3 #

**Comment by thomas-maeder** [comment]
Ironically, intelligent mode finds them all.

It seems that non-intelligent mode stops searching for longer continuations after 1.Sb5-d4 once a short one has been found.

**Comment by thomas-maeder** [comment]
Fixed for 4.87
