### ISSUE TITLE
StartMoveNumber in Intelligent mode

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#303]
What does `option StartMoveNumber` do in `Intelligent` mode?  It would seem natural for it to cause Popeye to begin searching at that depth (or perhaps one more or one less than that depth), but it doesn't seem to have that effect when solving seriesmovers.  I can't tell if nonzero values affect solving, but they do seem to (somehow) disable output from `option movenumbers`, at least until the last iteration.

**Comment by thomas-maeder** [comment]
Interesting question...

I don't think that currently, `option StartMoveNumber` does anything useful in intelligent mode.

And I agree that intuition tells us that the effect, if any, should be to start at a depth that is higher (lower? :-) ) than the minimal depth. I.e. as if we indicated a minimal length using a structured stipulation, e.g.: `sstip black 8:12hh[#]`

**Comment by thomas-maeder** [comment]
@JoshuaGreen Does this make sense?

**Comment by thomas-maeder** [comment]
Implemented for 4.91
