### ISSUE TITLE
macOS Binary

### ISSUE THREAD

**Issue by eikob** [thomas-maeder/popeye#304]
Compilation for macOS was indeed a bit tedious, especially without being a make wizzard. Anyway, I succeeded by compiling by hand. I've (temporarily?) made this build available here:

https://www.dropbox.com/s/flodhyib62awyoi/popeye-4.85-macos.zip?dl=1

It is a universal app, including slices both for x86 and arm. Feel free to add the binary it to your release page.

Compilation was the following (after removing some unused files, i.e. in DHT and platform)
```
# on x86 machine
clang **/*.c -I . -target x86_64-apple-macos10.12 -D NDEBUG -D FXF -D SIGNALS -D VERSION=4.85 -Ofast -o popeye.x86_64
# on arm machine
clang **/*.c -I . -target arm64-apple-macos11 -D NDEBUG -D FXF -D SIGNALS -D VERSION=4.85 -Ofast -o popeye.arm
# pack it together
lipo -create -output py popeye.x86_64 popeye.arm
```

**Comment by eikob** [comment]
4.87 for macos:
https://www.dropbox.com/s/id6tdi7xb4pju4g/popeye-4.87-macos.zip?dl=1

**Comment by thomas-maeder** [comment]
Thanks!
