### ISSUE TITLE
The 'sis->valueOffset' variable was assigned the same value. hash.c 411

### ISSUE THREAD

**Issue by mcroitor** [thomas-maeder/popeye#305]
After checking code, found in hash.c (from line 399 to line 411):
```C++
unsigned int const save_valueOffset = sis->valueOffset;

slice_index const op1 = SLICE_NEXT1(fork);
slice_index const op2 = SLICE_NEXT2(fork);

TraceFunctionEntry(__func__);
TraceFunctionParam("%u",fork);
TraceFunctionParamListEnd();

slice_properties[fork].valueOffset = sis->valueOffset;

stip_traverse_structure(op1,st);
sis->valueOffset = save_valueOffset;
```

As we can see, at line 399 save_valueOffset value sis->valueOffset was stored, at line 411 this value was restored. For sure, no changes in logic, but, may be, you wanted to write something else here?

**Comment by JoshuaGreen** [comment]
It looks like you're performing similar to analysis to that which I performed last summer.&nbsp; Great!

I'm sure I saw warnings like this one, but my assumption here (whether I saw this case then or just now) would be that
```c
stip_traverse_structure(op1,st);
```
on line 410 changes `sis->valueOffset` during its execution and that this function _intends_ to restore the original value.&nbsp; To me, this certainly doesn't _look_ like an accident.

**Comment by mcroitor** [comment]
Good question here. I've checked function **stip_traverse_structure**. This function calls another function **stip_structure_visit_slice**, no other visible possible modifications of **sis->valueOffset**. But stip_structure_visit_slice contains expression:
`(*operation)(si,st);`

**Comment by thomas-maeder** [comment]
> the code here intends to restore the original value.  To me, this certainly doesn't look like an accident.

This is exactly the intention, yes.
