### ISSUE TITLE
Expression 'state->guard_needed' is always false. selfcheck_guard.c 430

### ISSUE THREAD

**Issue by mcroitor** [thomas-maeder/popeye#306]
File selfcheck_guard.c, lines 426-435:
```C++
  state->guard_needed = false;

  stip_traverse_structure_children_pipe(si,st);

  if (state->guard_needed)
  {
    slice_index const prototype = alloc_selfcheck_guard_slice();
    slice_insertion_insert(si,&prototype,1);
    state->guard_needed = false;
  }
```
if condition (line 430) is always false, block will never be executed.

**Comment by JoshuaGreen** [comment]
My assumption here would be that
```c
stip_traverse_structure_children_pipe(si,st);
```
might change `state->guard_needed` by operating through the relevant pointers.&nbsp; This code looks intentional to me.

**Comment by mcroitor** [comment]
For sure, but i've checked stip_traverse_structure_children_pipe for this type of operations. May be, this flag is modified more deeper (by example, at stip_traverse_structure ).

**Comment by thomas-maeder** [comment]
> This code looks intentional to me.

It is. In fact determining whether a guard is needed is the purpose of recursing into the children.
