### ISSUE TITLE
Bug in CheekToCheek condition?

### ISSUE THREAD

**Issue by nshram** [thomas-maeder/popeye#309]
In this position: WKc8, WBa3, WPg5; BKe8, BBf6, BPf5; White can mate in 1 by 1.g6#!  But Popeye gives no solution.
If we add a BBh6 then Popeye gives 1.g6# as a solution.

Another test position: WKc8, WPc6; BKa8, BRb6, BSb7, BPa7; #1 by 1.c7#! But here too Popeye says no solution.
If we add BSd7 then 1.c7#! is accepted as a solution.

Is this a bug or am I missing something?

EDIT: It looks like Popeye is interpreting CtC as "...when two pieces of opposite colours stand adjacent to each other on the same rank, they transfer their powers to each other, while also _**retaining**_ their original powers". But this seems to be against the rule in the related conditions: BackToBack, FaceToFace and Point Reflection, where the pieces **_lose_** their original powers.

**Comment by thomas-maeder** [comment]
Definitely a bug.

begin
pieces white kc8 ba3 pg6 black ke8 bf6 pf5
stipulation ~1
condition cheektocheek
option noboard halfduplex
end

shows that Popeye simply moves the bishop away as a bishop to remove the bishop powers from the pawn.

The analoguous thing doesn't happen in FaceToFace or BackToBack.

**Comment by thomas-maeder** [comment]
Fixed for 4.87
