### ISSUE TITLE
Solution to SneK-problem not found 

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#310]
Anfang
Forderung H#2
Bedingung SnekSchach 
Option  Varianten MaxLoesungen 8 
Steine
Weiss   Kf5 Tb5 Lb6 Bd6
Schwarz Kd4 Sc5
Ende

Popeye 4.83 only finds the simple solution   1.Kd4-c3 Lb6*c5[c3=kS]   2.kSc3-d5 Lc5-d4 #
not the nice Knight-wheel  1. Kd4-d3 Tb1 2. Se4 K*e4(d3=kS)#

**Comment by thomas-maeder** [comment]
Thanks. Just fixed for 4.87.
