### ISSUE TITLE
Promotion missed in intelligent mode

### ISSUE THREAD

**Issue by Laborczi** [thomas-maeder/popeye#311]
In a series-helpstalemate Popeye does not find a promotion dual in intelligent mode.
In the following example, twin a) shows a case where Popeye does not find a solution which starts with 1.g5 and has a queen promotion in move 11. Interestingly, Popeye works correctly after a minor change,  see twin b).     
 
**Example Popeye input**:
*BeginProblem
Pieces
White Bh8 Kb5 Pd3 Qe3
Black Pg7 Pd5 Pe5 Ka1
Stipulation ser-h=12
Option Intelligent
Twin Move g7 g6
EndProblem*

**Popeye solution** (v4.85)
*a) 
  1.e5-e4   2.e4\*d3   3.d3-d2   4.d2-d1=R   5.Rd1-d4   6.g7-g5   7.g5-g4   8.g4-g3   9.g3-g2  10.g2-g1=Q  11.Qg1-d1  12.Qd1-b3 + Qe3\*b3 =
  1.g7-g5   2.g5-g4   3.g4-g3   4.g3-g2   5.g2-g1=R   6.Rg1-g4   7.Rg4-d4   8.e5-e4   9.e4\*d3  10.d3-d2  11.d2-d1=B  12.Bd1-b3 Qe3\*b3 =*

*b) bPg7-->g6  
  1.g6-g5   2.g5-g4   3.g4-g3   4.g3-g2   5.g2-g1=R   6.Rg1-g4   7.Rg4-d4   8.e5-e4   9.e4\*d3  10.d3-d2  11.d2-d1=Q  12.Qd1-b3 + Qe3\*b3 =
  1.g6-g5   2.g5-g4   3.g4-g3   4.g3-g2   5.g2-g1=R   6.Rg1-g4   7.Rg4-d4   8.e5-e4   9.e4\*d3  10.d3-d2  11.d2-d1=B  12.Bd1-b3 Qe3\*b3 =*

**Comment by thomas-maeder** [comment]
Thanks! This bug has already been fixed for 4.87.
