### ISSUE TITLE
Defence 0

### ISSUE THREAD

**Issue by dturevski** [thomas-maeder/popeye#314]
```BeginProblem
Stipulation #2
Option Defence 0
Pieces white Pc7 Kc6 black  Ka7
EndProblem

1.c7-c8=R !
```
expected:
```
1.c7-c8=Q ?   # <-- doesn't work, exactly 0 black defenses refute, matches the Defence option contract
1.c7-c8=R !
```

**Comment by thomas-maeder** [comment]
This is not how option defence works.

With option try but without option defence, Popeye writes a first move as a try if it is refuted by 1 defence.

With option defence N, Popeye writes a first move as a try if it is refuted by between 1 and N defences.

Not selecting option defence with option try can be considered thte special case of setting N to 1.

**Comment by dturevski** [comment]
Thanks. So there is no way of listing tries that are refuted by zero defenses (eg stalemates in directmates or checkmates in selfmates).

**Comment by thomas-maeder** [comment]
There is always a way.

E.g. interpreting "defence 0" the way you suggest would hardly break anything.
