### ISSUE TITLE
PSer-S=2 not solved

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#318]
Anfang
Forderung PSer-S=2
Steine
Weiss   Kh1 Dg6
Schwarz Kc7 Bg3 Bh2 Bh3
Ende
This simple PSer-S=2 has no solutions according to Popeye 4.87, but 1. Dc6 Kb8/Kd8  2. Db7/Dd7 KxD= seems to be perfectly legal solutions. 
After Dc6 Kb8/Kd8 Popeye solves a PSer-S=1

**Comment by thomas-maeder** [comment]
After 1.Dc6+, Black defends with Kxc6.

If you want helping parry moves, you have to ask for it: phser-s=2

**Comment by JoshuaGreen** [comment]
@thomas-maeder, I must not understand this stipulation.  1. ... Kxc6 delivers the stalemate that White is trying to force, so how is it a defense?

**Comment by BjornEnemark** [comment]
I am sorry, I don't understand
You write that after 1. Dc6+ Black defends with Kxc6 - but then White is stalemate in one. So Kxc6 must be a helping move!
Black should try to postpone or avoid the self stalemate, as I see it.

**Comment by thomas-maeder** [comment]
Oh - it seems that I was too quick with my reply then.

**Comment by JoshuaGreen** [comment]
(As you've added the bug tag, I feel it's appropriate to reopen this issue.)

**Comment by thomas-maeder** [comment]
Fixed for 4.89
