### ISSUE TITLE
Bug in NorskSjakk, introduced in 4.77 and persist in 4.87

### ISSUE THREAD

**Issue by vaclavko** [thomas-maeder/popeye#321]
While I testing the originals for Czech journal Sachova skladba, I encountered the following bug.

Anfangproblem
Protokoll ss152py.txt
Autor Imrich BANDZUCH
Quelle Sachová skladba 2021
Forderung h#4
Steine Weiss Ke1 Ta1
Steine Schwarz Ke3 Sg6 Bg3 Bh4
bed NorskSjakk
Option WeissBeginnt Zugnummern MaxLoesungen 100
EndeProblem

Versions 4.73 and 4.75 found two solutions
1...Ta1-a8=L   2.Ke3-f4 La8-h1=T   3.Kf4-g4 0-0   4.Kg4-h3 Tf1-f5=L #
1...Ta1-a7=L +   2.Ke3-f3 Ke1-d2   3.Sg6-f4=D + Kd2-d3   4.Df4-g4=S La7-f2=T #

But versions 4.77, 4.79, ..., 4.85 found only one solution
1...Ta1-a7=L +   2.Ke3-f3 Ke1-d2   3.Sg6-f4=D + Kd2-d3   4.Df4-g4=S La7-f2=T #
[BUGpopeye.zip](https://github.com/thomas-maeder/popeye/files/7271378/BUGpopeye.zip)

**Comment by vaclavko** [comment]
Interestingly, WinChloe also found only one solution.

**Comment by thomas-maeder** [comment]
Surprisingly, the difference between the older and the current versions is not that Popeye wouldn't castle with the Norsk rook, but that newer versions don't do 0-0, but 0-0=L!

This was the topic of issue #214 .

**Comment by thomas-maeder** [comment]
Not a bug.
