### ISSUE TITLE
apparent bug in postkeyplay

### ISSUE THREAD

**Issue by andrew-buchanan** [thomas-maeder/popeye#322]
Hi working from Olive and Popeye v4.87, I asked about P1142517:
BeginProblem
Stipulation #3
Option Variation NoBoard PostKeyPlay
Pieces
  white  Qb1 Kd5 Sf7d7 Pe7
  black  Ke8
EndProblem

The answer given is:
 threat:
          2.Qb1-f5 zugzwang.
              2...Ke8*e7
                  3.Qf5-e6 #
      1...Ke8*d7
          2.Qb1-b7 +
              2...Kd7-e8
                  3.Sf7-d6 #
      1...Ke8*f7
          2.Qb1-h7 +
              2...Kf7-e8
                  3.Sd7-f6 #
                  
This is missing a solution. If I additionally set Nothreat, I see       
      1...Ke8*d7
          2.Qb1-b7 +
              2...Kd7-e8
                  3.Sf7-d6 #
      1...Ke8*f7
          2.Qb1-h7 +
              2...Kf7-e8
                  3.Sd7-f6 #
      1...Ke8*e7
          2.Qb1-f5
              2...Ke7-e8
                  3.Qf5-e6 #

with the expected third solution beginning 1...Ke8*e7. Please can you tell me if this expected behaviour or what?

Thanks so much for all your work!
Andrew

**Comment by thomas-maeder** [comment]
Yes, this is expected behaviour.

1.-Ke7: doesn't defend against the threat 2.Qf5.
