### ISSUE TITLE
bug in intelligent for h#5

### ISSUE THREAD

**Issue by andrew-buchanan** [thomas-maeder/popeye#324]
Hi v4.87 (via Olive v1.4 ) for PDB problem P0003325 h#5 delivers the correct solution with en passant set to f2f3f4. However no solution when the "intelligent" flag is also set.

BeginProblem
Stipulation h#5
Option Variation NoBoard EnPassant f2f3f4
Pieces
  black  Pa5b3g4b2c3f5d7a7 Se1c8 Ba1e6 Ke4
  white  Pf4g2a2a3a4 Kb1
EndProblem
Popeye Windows-64Bit v4.87 (1024 KB)
  1.g4*f3 ep. g2-g4   2.Ke4-d5 g4*f5   3.Kd5-c6 f5*e6   4.Kc6-b7 e6*d7   5.Kb7-a8 d7*c8=Q #
solution finished. Time = 2:13.376 m:s
BeginProblem
Stipulation h#5
Option Variation NoBoard EnPassant f2f3f4 Intelligent
Pieces
  black  Pa5b3g4b2c3f5d7a7 Se1c8 Ba1e6 Ke4
  white  Pf4g2a2a3a4 Kb1
EndProblem
Popeye Windows-64Bit v4.87 (1024 KB)
solution finished. Time = 0.142 s

Hardly urgent, but worth reporting. Thanks for all your work! :)

**Comment by thomas-maeder** [comment]
With run time checks enabled, Popeye prints the following error message:
py: position/effects/piece_removal.c:33: Assertion `!is_square_empty(from)' failed.

This used to work until 4.69.

**Comment by thomas-maeder** [comment]
Fixed for 4.89.

Then run time check was a different bug triggered by this problem; also fixed.
