### ISSUE TITLE
MoveNumber output bug

### ISSUE THREAD

**Issue by popeye37** [thomas-maeder/popeye#333]
version 4.87 (maybe earlier also ...)
(any) position, example: wKf6 wPa3; bKg8 bSh8 bPf7
stipulation: hr#2, option: movenumber => output as expected, 9 movenumbers shown
stipulation: hr#2.5 (ie. black to move first) , option: movenumber => more than 338 movenumbers shown, which is wrong.

Looks like if hr# is used with x.5 moves, not only the first halfmove is shown by movenumbers, but also the reflex moves tried during solving ...
Btw. hs#2.5 is ok.

**Comment by thomas-maeder** [comment]
In addition, every move given with the move numbers is "decorated" with a check marker ('+').

**Comment by thomas-maeder** [comment]
Fixed for 4.89
