### ISSUE TITLE
Piece "Dabbaba" is misspelled in pie-engl.txt as "Dabbabba"

### ISSUE THREAD

**Issue by edderiofer** [thomas-maeder/popeye#334]
As per the title. It seems that the more common spelling by far is the former one, with only three Bs, while `pie-engl.txt` lists the latter one, with four Bs.

**Comment by thomas-maeder** [comment]
Swedish pop music is very influential... :-)

**Comment by thomas-maeder** [comment]
Unified spieling for 4.89
