### ISSUE TITLE
castling costs a move

### ISSUE THREAD

**Issue by JoshuaGreen** [thomas-maeder/popeye#345]
Should `withcast` computed on lines 70, 76, 103, and 109 of [`optimisations/intelligent/count_nr_of_moves.c`](https://github.com/thomas-maeder/popeye/blob/master/optimisations/intelligent/count_nr_of_moves.c) be incremented by 1 since castling _itself_ takes a move?

As long as I'm asking about castling in this file, I might as well ask another question.&nbsp; There's a good chance I'm simply clueless here, but why are lines 68 and 74 so different from lines 101 and 107 (respectively)?&nbsp; I'd expect similar logic in each case.&nbsp; (Of course, maybe these _are_ equivalent and I just don't realize why.)

**Comment by thomas-maeder** [comment]
The suggestion in the 1st paragraph seems to make sense, but if we add +1 on the 4 lines mentioned, the following solutions are no longer found in the examples:
castling.out:
1...Kf4-e4   2.Dh8-h2 Ke4-d5   3.0-0-0 + Kd5-c6   4.Dh2-b8 Sf5-e7 #
intell.out:
1.c4-c3 Le2-f3 +   2.Ke4-d3 Lf8*h6   3.Dh4-c4 0-0-0 #
1.Ke4-d3 g2*f3   2.Dh2-a2 Ld8-g5   3.Da2-c4 0-0-0 #
1.0-0 Se3-d5   2.Db2-h8 Lf1-c4   3.Lh6-g7 Sd5-f6 #
1.0-0-0 Se3-c4   2.Db2-b8 Tf1-c1   3.Sa5-b7 Sc4-b6 #

**Comment by JoshuaGreen** [comment]
I looked up how I handled the "castling costs a move" issue in my experimental [`feature/optimize_intelligent_mode_count_moves`](https://github.com/JoshuaGreen/popeye/tree/feature/optimize_intelligent_mode_count_moves) branch of [my fork](https://github.com/JoshuaGreen/popeye).&nbsp; There I have an outer loop over all the pieces on the board, and my solution is to treat castling as a Rook move.&nbsp; Inside the loop I determine the minimum number of extra Rook moves that castling entails, and later I contrast that with the maximum number of King moves that castling can save; this allows me to determine if castling can be a net benefit.

I don't know if the main Popeye logic allows something similar to be done more generally.
