### ISSUE TITLE
Possible error caused by the combination Marscirce+Isardam?

### ISSUE THREAD

**Issue by WalterL-wL** [thomas-maeder/popeye#350]
At Julia's a fascinating problem was published recently ([JF-1739](https://juliasfairies.com/problems/no-1739/#comment-53269)). Popeye is said to have resulted in C- , so I tried to find out why. The original is with stipulation hs#2 and 2 solutions (FEN: b7/4PP2/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3). I also tried focused variations with stipulations h#1 and also #1 for both situations separately (FEN for a: b4Q2/4P3/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3), (FEN for b: b3R3/5P2/2B5/6p1/7K/2p1P1PP/p1Pk1P2/3sR3). The "results" are partly unexplainable in my opinion...

begin
stip ...
cond marscirce isardam
opti vari move
Forsyth ...
End

Some can be explained with an assumed priority of Marscirce over Isardam (especially in case of KxK), but not all of them...

**Comment by WalterL-wL** [comment]
My tests seem to show that Popeye sets a priority for Marscirce over Isardam (equally for Anticirce over Isardam). Such, the (interim) rebirth square of the Marscirce capture move is not scanned for an illegal Isardam observation, the scan will only happen at the end of this Marscirce capture move. Here this often happens especially in the different situations with KxK (via an emptied e1). So, subsequently I will not refer to any situation that can be explained by this priority handling, but I will concentrate on the few other situations in the "results lists" (source code see before) that are unexplainable to me (hopefully it's not my misjudgement):

An initial thought: I do NOT think those differences have to do with the specific diagram positions of bBa8 versus wBc6? They should NOT observe each other under the condition Marscirce (no matter if primary or secondary priority). So there should be no illegal Isardam observation as a consequence, both (especially wBc6) should be free to move... or does Popeye still see it differently based on its priority regime!? Equally, given bRh4 and wRe8 (no pieces in between) should not establish an Isardam situation, because first it would take a Marscirce capture move bRxwR, resulting in an interim rebirth square h8 for bR, but as Marscirce has priority over Isardam and once this capture move (bRh4 x wRe8 (via h8)) is finished, there is no Isardam situation any more left...!?

1.) FEN: b7/4PP2/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
stipulation hs#2:
...
23  (e7-e8=S +    Time = 0.343 s)
--> So, wSe8 now checks bKd2 (via b2), and as e8 is still occupied by wS (during the threat!) the bK cannot escape by a Marscirce capture move on his own (via e8), or escape to c1 (attacked by wRe1 via a1), or escape to d3/e2 (attacked by wBc6 via f1), or be defended in any other way [the virtually(!) interim positioned wB "via b2" would neither block wRe1 (via a1) against the bKd2-c1 escape try, nor could it be captured by bPa2...], nor would the capture of the bKd2 establish any resulting Isardam situation...; so this should establish checkmate with the first move (# instead of +) in my opinion!


2.) FEN (ref. solution a): b4Q2/4P3/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
2.1) stipulation h#1:
... apart from those several illegal selfcheckmate situations of the bK, like 1  (Sd1-g8xe7), or 8/9/10  (Kd2-c1/d3/e2), which are not marked as # or as illegal in any way, there are no further unclear situations...

2.2) stipulation #1:
...
21  (e7-e8=S +    Time = 1.148 s)
--> same situation as above at 1.) ... so this should establish checkmate with the first move (# instead of +) in my opinion!


3.) FEN (ref. solution b): b3R3/5P2/2B5/6p1/7K/2p1P1PP/p1Pk1P2/3sR3
3.1) stipulation h#1:
1  (Sd1-b2    Time = 0.130 s)
...
1.Sd1-b2 f2-f3 # (and all the 13 following checkmate "solutions", except ...f8=Q and ...f8=B)
--> as long as wRe1 has NOT left its square, there is no attack (via Marscirce) by the wKh4, nor by any other w stone. So, how else could the black move Sd1-b2 initiate a following checkmate situation in all those cases (except when one of those two white moves would follow with ... f8=Q or ... f8=B)?

Of course, a bS on a dark square (b2) could later(!!!) capture wBc6 (via b8) and such free squares d3 and e2 of being forbidden for the bK in his escape try. But this would not result in a checkmate (#) already in the first move!?

And further, in the "results list" there is one technically possible w move missing: 
1.Sd1-b2 Bc6-h1 - WHY? The (interim) rebirth field h1 of a wR (light square) does not seem to have any importance here?

And what about 1.a1=R# ? Isardam (on h8) should not be a problem here, because Marscirce has priority (checkmate wKh4 via h8)!? Of course it's a stipulation h# (and not to capture the wK) but the move would be legally executable...? And the resulting situation bRh4 versus wRe8 might not establish an Isardam situation either, because there is no direct observation and Marscirce has again priority (so, bR x wR...)!?

3.2) stipulation #1:
...
22  (f7-f8=B +    Time = 0.164 s) 
--> the wBf8 attacks bKd2 via c1; there is no escape or defense for the bK (an escape move bKd2-c1 would be selfcheck due to wRe1 (via a1)...); so this should establish checkmate with the first move (# instead of +)!

...Actually Popeye DOES present a correct checkmate with the first move (as #) in the upper lines of the results here:
2  (Re1-a1xd1 +    Time = 0.110 s)
   1.Re1-a1xd1 # !

Many unclear issues... Thanks for a review!

**Comment by WalterL-wL** [comment]
Exzerpts of additional **striking** "(lax) test"-results (cond isardam marscirce), may be they can further help in identifying the bug:

stip#2, opti vari move, FEN b7/4PP2/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
  7  (f2-f4    Time = 0.109 s)	<-- WHY no + (like all the others following)?
  8  (f2-f3 +    Time = 0.109 s)	<-- WHY with + (like all the following ones)?
  9  (e3-e4 +    Time = 0.125 s)	<-- **WHY g3-g4 is missing??** Under priority for Marscirce (-->Pawn rebirth on initial square!) there is no Isardam situation left???
11  (Kh4-g4 +    Time = 0.125 s)		<-- Selfcheckmate!?

stip#2, opti vari move, FEN b4Q2/4P3/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
21  (e7-e8=S +    Time = 0.187 s)	<-- This is # (not +)?

stip#2, opti vari move, FEN b3R3/5P2/2B5/6p1/7K/2p1P1PP/p1Pk1P2/3sR3
21  (f7-f8=R +    Time = 0.171 s)
   1.f7-f8=R # !			 	<-- WHY # ?
22  (f7-f8=B +    Time = 0.187 s) 	<-- This is # (not +)?

stip#2, opti vari move setplay, FEN b7/4PP2/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
      1...Kd2-e1				<-- WHAT?, **e1 is actually occupied!?**
          2.e7-e8=R #
the side to play can capture the king

stip#2, opti vari move Duplex, FEN b7/4PP2/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
21  (e7-e8=S +    Time = 0.168 s)	<-- This is # (not +)?
27  (f7-f8=B +    Time = 0.187 s)	<-- This is # (not +)?
38  (Kd2-d3    Time = 0.251 s)		<-- Selfcheckmate!?
39  (Kd2-e2    Time = 0.253 s)		<-- Selfcheckmate!?

stip#2, opti vari move Duplex, FEN b4Q2/4P3/2B5/7p/7K/2p1P1PP/p1Pk1P2/3sR3
45  (Kd2-e1    Time = 0.274 s)		<-- WHAT?, **e1 is actually occupied!?**
46  (Kd2-d3    Time = 0.277 s)		<-- Selfcheckmate!?
47  (Kd2-e2    Time = 0.280 s)		<-- Selfcheckmate!?

stip#2, opti vari move Duplex, FEN b3R3/5P2/2B5/6p1/7K/2p1P1PP/p1Pk1P2/3sR3
21  (f7-f8=R +    Time = 0.197 s)
   1.f7-f8=R # !				<-- WHY # ?
22  (f7-f8=B +    Time = 0.202 s)	<-- This is # (not +)?

stip hr#2, opti vari move Duplex, FEN b3R3/5P2/2B5/6p1/7K/2p1P1PP/p1Pk1P2/3sR3
22  (f7-f8=B +    Time = 0.158 s)	<-- This is # (not +)?...
36  (a2-a1=B    Time = 0.232 s)		<-- missing a1=R , resulting in checkmate
...
  1.Sd1-b2 f7-f8=Q #			<-- OK!
  1.Sd1-b2 f7-f8=S #			<-- WHY # ?
  1.Sd1-b2 f7-f8=R #			<-- WHY # ?
  1.Sd1-b2 f7-f8=B #			<-- OK!
...
46  (Kd2-e1    Time = 1.401 s)		<-- WHAT?, **e1 is actually occupied!?**

**Comment by thomas-maeder** [comment]
Not a bug, but, as the solution mentions: Popeye has a different concept of observation
