### ISSUE TITLE
Possible error with Rankcirce?

### ISSUE THREAD

**Issue by WalterL-wL** [thomas-maeder/popeye#351]
While exploring the scope of **Rankcirce** I found two striking problems in PDB: problem A ([P1296038](https://pdb.dieschwalbe.de/search.jsp?expression=probid%3D%27P1296038%27)) and problem B ([P1336237](https://pdb.dieschwalbe.de/search.jsp?expression=probid%3D%27P1336237%27)). Both from the same author, both indicate C+ (Popeye v4.59) - the strange issue: the applied interpretation of 'rebirth square' under Rankcirce seems to differ fundamentally within the *same* release!

Problem A (ser-=14) **can** be reproduced with the current version 4.87 of Popeye and shows the correct solution with (repeated) rebirth squares with the same color as the capture square on the same row (e.g. 3.wRa6×Sa5[bS**g5!**]). Seems ok!

Problem B (h#2 2.1...) **cannot** be reproduced with the current version 4.87 of Popeye and shows NO solution at all. Although, PDB presents TWO solutions (said to be equally derived from Popeye vers. 4.59), BUT here the rebirth squares on the same row seem to be defined by the capture square's color on the *own* original officers' row projected to the capture row, e.g.:
- solution 1: 2.nRa1×nSa8[nS**b8!??**] - evidently the proper 'wS' is reborn as 'projected' from b1 to b8, its rebirth on b8 is essential for the solution (instead of g8) as a temporary blocking piece!
- solution 1+2: at the end of move 2 a nR is positioned on b8 vis-a-vis a bKc8 and an empty square a8 resulting in Checkmate; here the assumed (illegal defense) 3.bKc8×nRb8[nR**a8!??**]# would not change the Checkmate, because of its rebirth on a8 (instead of h8, where Checkmate would be obstructed on f8)...

~~- **BUT** even if you applied in problem B the *diverging* rebirth square interpretation of problem A, there should be ONE single solution with 2.nBe5-b8 nPa7×b8=**nQ**[nBf8]#, as the nQ would be reborn on d8 anyhow in case 3.bKc8×nQb8[nQ**d8!**]# (and if the bK instead moves to d8 then capture by the nQb8 should have priority over an occupied d8)...~~
~~I even tried to simplify the situation as follows: stip#1, cond rankcirce, pieces wKc6, bKc8, bSb7, bBb8, nPa7; but again Popeye 4.87 does NOT present the existing solution 1.nPa7×bBb8=**nQ**[bBf8]#~~

~~I assume there is an erroneous handling in Popeye of this concurrence of neutral pieces capturing each other with promotion and being reborn, color of square for rebirth, etc...?~~

**Comment by ildjarnisdead** [comment]
Walther,

1. ab8=nQ isn't mate, as the neutral queen can just move away to e.g. a7.

**Comment by WalterL-wL** [comment]
> 1. ab8=nQ isn't mate, as the neutral queen can just move away to e.g. a7.

Oops... **Thanks!**  I ~~deleted~~ part of my former comment...

**Comment by WalterL-wL** [comment]
Oops..., mymistake! So, there is no problem left... I closed the issue. THANKS!


    Am Montag, 8. Mai 2023 um 21:37:49 MESZ hat ildjarnisdead ***@***.***> Folgendes geschrieben:  
 
 


Walther,
   
   - ab8=nQ isn't mate, as the neutral queen can just move away to e.g. a7.
