### ISSUE TITLE
Bug in kxy?

### ISSUE THREAD

**Issue by ildjarnisdead** [thomas-maeder/popeye#353]
begin
pie whi kh1 ph2
bla rg8 ka8
stip hkg81
twin rem h1
end

a) has 5 solutions, b) has 6. The missing solution in a) is 1. Rg2 h3 which I think is a valid solution in a) because h3 is a square around g2.
Or am I understanding kiss incorrectly, and should only 1 square be occupied?

**Comment by nshram** [comment]
See this link: http://matplus.net/start.php?px=1691852111&app=forum&act=posts&fid=xshowf&tid=3040

**Comment by thomas-maeder** [comment]
I have looked at the code that implement the test whether the piece to be kissed has just been kissed.
This test includes the condition that the piece to be kissed be "naked", i.e. all squares adjacent to it apart from the kisser's position have to be empty.
I can't find the correspondence that led to the implementation of goal kiss, but I am sure that this condition was put in on purpose.
