### ISSUE TITLE
bug: combining phantomchess and genevachess

### ISSUE THREAD

**Issue by popeye37** [thomas-maeder/popeye#354]
BeginProblem
Stipulation +1
Condition GenevaChess PhantomChess
Pieces
  white  Pb6 Kc8
  black  Pa7 Ka8
EndProblem

no solution above ...

using stipulation =1
the wrong (?) solution is  1.b6-b7 = !

setting the wPb6 to b7 gives error message:   " the side to play can capture the king"
so if white can capture the black king with wPb7, then the move wPb6-b7 cannot be stalemate ...

Other example:
BeginProblem
Stipulation +1
Condition GenevaChess PhantomChess
Pieces
  white  Kc8 Qb1
  black  Pa7 Ka8
EndProblem

4 Solutions:  
1.Qb1-e4 + ! 
1.Qb1-b8 + ! 
1.Qb1-b7 + !
1.Qb1-h1 + !
Why not 1.Qb1-d1-d5 + ! and 1.Qb1-d1-f3 + !    ??

Using the stipulation =1
we get 2 solutions:
1.Qb1-d1-f3 = !
1.Qb1-d1-d5 = !
which also look wrong ...

**Comment by popeye37** [comment]
I'm sorry I forgot to mention the Popeye version:
vAndernach-2022-4.88
Windows and Linux version behave the same.

**Comment by thomas-maeder** [comment]
Fixed for 4.89
