### ISSUE TITLE
SeriesCapture proof game found no solution

### ISSUE THREAD

**Issue by MuTsunTsai** [thomas-maeder/popeye#378]
The following input gives no solution:
```
begi
fors rsbqkbsr/p1pppppp/1P6/8/8/8/1PPPPPPP/RSBQKBSR
stip dia1.5
cond series
end
```
while expecting 1.a4 b5 2.axb5-b6
(Reported by Andrew Buchanan)

The weird part is that if I enter the position after 1...b5 and use `stip ~1`, it does list 2.axb5-b6 as a legal move.

**Comment by thomas-maeder** [comment]
Fixed for 4.91
