### ISSUE TITLE
Popeye. When you want "black to play" in a hs (helpself) problem, this can only be done by selecting option "WhiteToPlay". This is confusing.

### ISSUE THREAD

**Issue by Wiereyn** [thomas-maeder/popeye#439]
BeginProblem
Protocol	 vZUu2
Author		 Zujevas, Nikolaius
Origin		 Sachmatija, 3/2505; date: 2012
Title		 intended-solutions: 2
Pieces White	 Kd1 Rd3 Pc3
Black		 Ka1 Rb4 Bf1 Pa4
Stipulation	 hs#4
Option		 SetPlay
EndProblem
   1) 1..a3 2.Kc2 Ra4 3.Kb3 Be2 4.Rd1+ B: d1# 2) 1..Rb1+ 2.Kc2 Rd1 3.Rd4 Bb5 4.R: a4+ B: a4#

See above problem. When Popeye solves this problem, endless solutions are first found with white to play, before the intended 2 solutions are found with black to play, so the Option "SetPlay" is not correct here.
If "NullMoves" is tried as an option, no solution is found.
However, there is no option: BlackToPlay.
In Alybadix you have a choice between 'with setplay' and 'only setplay'.
In my desperation, I finally tried the option: WHITE  ToPlay  in this problem and to my surprise Popeye now produced only the intended 2 solution, with 'BLACK to play.
This is, of course, confusing.
This issue could be solved by adding a 'BlackToPlay' option, or renaming/describing the 'WhiteToPlay' option to show that the opponent starts.
Further I draw your attention to 3 small typing errors in the file "py-engl.txt"
"seperated by blanks" must be "separated ..."
"blank seperated list" must be "blank separated list"
"Servers for finding tempo tries." must be "Serves ....."

**Comment by dturevski** [comment]
Maybe `Stipulation hs#3.5` is what are you looking for?

**Comment by dturevski** [comment]
In fact, this problem was originally published with stipulation hs#3.5:
https://sachmatija.puslapiai.lt/dokai/uzdaviniai3.2012.pdf

**Comment by thomas-maeder** [comment]
I have never understood why some authors (particularly the Germans) insist on writing e.g. "h#4 Weiß beginnt", since h#3.5 seems clearer and more precise.

"Stipulation hs#3.5" works perfectly, so I don't see any need for action here.
