### ISSUE TITLE
Condition 'AntiCirce File' - reborn fairy pieces

### ISSUE THREAD

**Issue by WalterL-wL** [thomas-maeder/popeye#442]
While experimenting with different kinds of Anticirce subtypes I stumbled across the following situation in Popeye (v4.89), FR=fersrider (German notation):
ford h=3
bedi ***AntiCirce File***
Forsyth .FR6k/1b3B1B/8/8/8/8/5bbK/8
Opti vari zugn

Very many similar solutions were presented, like (e.g.):
1.g2-g1=D f7-f8=D +   2.Dg1-g8 h7×g8=D[wDg8->g1] +   3.f2×g1=S[sSg1->g8] FRa8×b7[wFRb7->b1] =
--> h7×g8=D[wDg8->g1] correct, a promoted orthodox w piece is reborn on row 1
--> f2×g1=S[sSg1->g8] correct, a promoted orthodox b piece is reborn on row 8
--> FRa8×b7[wFRb7->b1] **WRONG**, a capturing w fairy piece should be reborn on row 8!?

or:

1.g2-g1=D f7-f8=D +   2.Dg1-g8 h7×g8=FR[wFRg8->g1] +   3.f2×g1=FR[sFRg1->g8] FRa8×b7[wFRb7->b1] =
--> h7×g8=FR[wFRg8->g1] **WRONG**, a promoted w fairy piece should be reborn on row 8!?
--> f2×g1=FR[sFRg1->g8] **WRONG**, a promoted b fairy piece should be reborn on row 1!?
...etc... (many)...

As far as I know fairy pieces as capturers are regularly reborn in AntiCirce on their promotion rank, which should also be true in case of a *capturing pawn promotion=fairy piece* (resulting in no change of position). The additional option "File" would even be redundant with fairy pieces here. All the above **WRONGs** instead seem to follow an additional option "(File) Mirror"??? **[UPDATE: and also vice versa!]** - THANKS!

**Comment by WalterL-wL** [comment]
I forgot to mention something that might be important here. This time I worked with the German language version of v4.89. At first when I used the condition 'Antifilecire' I received an error message (although this is the given denomination in the German manual besides 'AntiCirce File', in English it's 'FileAntiCirce'):

Eingabe-Fehler:Bedingung nicht erkannt
Stoerende Eingabe: Antifilecire

Only after having changed to condition 'AntiCirce File' the error message was gone...

**Comment by thomas-maeder** [comment]
I have distilled the following minimal test case out of your first example:

```
begin
stip =1
cond AntiCirce File
pieces white kh2 qf8 ba8 black kh8 sg8 pb7
twin add white fra8
end
Popeye Linux-6.2.0-39-generic-x86_64-64Bit v4.90 (1024 MB)

+---a---b---c---d---e---f---g---h---+
|                                   |
8   B   .   .   .   .   Q  -S  -K   8
|                                   |
7   .  -P   .   .   .   .   .   .   7
|                                   |
6   .   .   .   .   .   .   .   .   6
|                                   |
5   .   .   .   .   .   .   .   .   5
|                                   |
4   .   .   .   .   .   .   .   .   4
|                                   |
3   .   .   .   .   .   .   .   .   3
|                                   |
2   .   .   .   .   .   .   .   K   2
|                                   |
1   .   .   .   .   .   .   .   .   1
|                                   |
+---a---b---c---d---e---f---g---h---+
  =1                          3 + 3
            AntiCirce File

a) 

   1.Ba8*b7[wBb7->b1] = !


b) wFRa8 

   1.FRa8*b7[wFRb7->b1] = !


solution finished. Time = 0.071 s
```
This definitively looks like a bug to me.
It looks as if Popeye treats a Fersrider like a bishop.

**Comment by thomas-maeder** [comment]
In fact, rebirth squares for fairy pieces were not only calculated wrong for Anticrce File, but also for Circe File!
