### ISSUE TITLE
Messy Messigny + PointReflection

### ISSUE THREAD

**Issue by adrianstori** [thomas-maeder/popeye#459]
BeginProblem
Pieces
White Gd7 Kf2
Black Gc7 Ka1
Stipulation ~1
Condition pointreflection messigny
EndProblem

shows 3 possible white moves:

(a) 1.Kf2<->Gc7 !
(b) 1.Gd7<->Gc7 !
(c) 1.Gd7-b7 !

(a) seems wrong, in Messigny same-**type** pieces can be interchanged, not same-**movement** pieces.  Kf2 has the reflected G movement power from Gc7, but it's still a king.

And then comes solution (b):  Gc7 has (symmetrically) K movement power, but it's now interchanged with a G.

I think some sort of an extended Messigny would be acceptable as a variant (pieces interchanging by both their type AND by their point-reflected power).  But in such a case, in the position above there is a missing solution 1.Kf2<->Ka1 !

**Comment by thomas-maeder** [comment]
@adrianstori Do you agree that this makes more sense?

```
BeginProblem
Pieces
White Gd7 Kf2
Black Ka1 Gc7
Stipulation ~1
Condition pointreflection messigny
twin add neutral Gc7
EndProblem
```

```
Popeye Linux-6.5.0-26-generic-x86_64-64Bit v4.90 (1024 MB)


+---a---b---c---d---e---f---g---h---+
|                                   |
8   .   .   .   .   .   .   .   .   8
|                                   |
7   .   .  -G   G   .   .   .   .   7
|                                   |
6   .   .   .   .   .   .   .   .   6
|                                   |
5   .   .   .   .   .   .   .   .   5
|                                   |
4   .   .   .   .   .   .   .   .   4
|                                   |
3   .   .   .   .   .   .   .   .   3
|                                   |
2   .   .   .   .   .   K   .   .   2
|                                   |
1  -K   .   .   .   .   .   .   .   1
|                                   |
+---a---b---c---d---e---f---g---h---+
  ~1                          2 + 2
            MessignyChess
           PointReflection

a) 

   1.Gd7-b7 !

b) nGc7  

   1.Gc7<->Ka1 !

   1.nGc7-b6 !

   1.nGc7-d6 !

   1.nGc7-d8 !

   1.nGc7-b8 !

   1.nGc7-c6 !

   1.nGc7-b7 !

   1.nGc7-c8 !

   1.Gd7-b7 !

solution finished. Time = 0.015 s
```

**Comment by adrianstori** [comment]
I still believe the Messigny moves should be the swap of same **type** of pieces (regardless of their current reflected moving capabilities) -- in both _a_ and _b_:  w**K**f2<->b**K**a1 and w**G**d7<->b/n**G**c7.

Your solution above seems to assume the Messigny swap is by **movement capability**.  But then the question still stands:  why not also wKf2<-> b/nGc7 in both twins (similar to the nGc7<->bKa1 you have in _b_)?

I wonder if anyone knows WinChloe's approach!?

**Comment by thomas-maeder** [comment]
What makes you prefer same (static) type over same (dynamic) movement type to be the decisive criterion?
Does the Messingy specification say so explicitly?

With my approach, we would have consistent behavior, which certainly is a progress compared to the situation up to 4.89.

> why not also wKf2<-> b/nGc7

Because these 2 pieces never share a common type nor a common movement.

**Comment by adrianstori** [comment]
> why not also wKf2<-> b/nGc7    Because these 2 pieces never share a common type nor a common movement.

You're right, my mistake.

Yes, your approach _is_ definitely an interesting option.  (And things do stand better than < v4.90.)

P.S. Just wondering whether this behaviour will be consistent with other cases of Messigny + power transfers?  (E.g., Is the PointReflection here similar to, say, Orphans, Transmuted Kings?)
