### ISSUE TITLE
Set play in one for self mates

### ISSUE THREAD

**Issue by BjornEnemark** [thomas-maeder/popeye#473]
In the problem below Popeye correctly finds the solution and a set play in two moves, but ignores a set play in one: 1. - dxe5#
For helpmates set play in one is found.
Anfang
Autor Georg Thomas
Quelle Springaren
Bemerkung FIDE Album 1945-1955 nr. 1188
Forderung S#2
Option  Satzspiel Varianten MaxLoesungen 8 
Steine
Weiss   Kd1 Dg4 Te8 Lb1 Se7 Sf8 Bb6 Bd4 Bg2
Schwarz Kd6 Lc1 Lf5 Sh1 Bb2 Bd2 Bd3 Bg3
Ende

**Comment by thomas-maeder** [comment]
I assume the missing set play is 1...Sh1-f2#

**Comment by thomas-maeder** [comment]
The variation 1....Sh1-f2# is also suppressed after the key.
It is intended behavior to suppress trivial self-play variations (i.e. variations in 1, and the number of remaining moves is >1), so I am removing the bug label again.
On the other hand, it is easy to add an option that allows users to prevent the suppression of trivial variations.
