### ISSUE TITLE
Better memory usage for chess problems with 4-6 pieces

### ISSUE THREAD

**Issue by vaclavko** [thomas-maeder/popeye#484]
I tested this WenigSteiner:
[https://pdb.dieschwalbe.de/P1416152](url)
Input file:
[lucehdp30input.txt](https://github.com/thomas-maeder/popeye/files/14892864/lucehdp30input.txt)
Solution:
[lucehdp30.txt](https://github.com/thomas-maeder/popeye/files/14892858/lucehdp30.txt)
Screenshot (include Windows Task Manager during solving):
![lucehdp30_wtm](https://github.com/thomas-maeder/popeye/assets/91785610/e79ec0cc-1489-4cf5-9a65-f374d5c76ccf)

With the condition that pawns can promote only into grasshoppers it's easy, Alybadix found the solution in 5 minutes. However, the maximum memory of 4 GB was not enough for the complete test. That's why I used the Popeye with -maxmem 350G (my computer has 384 GB RAM). The test took 112 hours and the problem is C+. 
 
There are only 4 pieces and the total number of possible positions (including illegal ones) is
64 * 65 * (65 * 6) * (65 * 6) = 632736000
However, the program used a total of 258 (!) GB of RAM. This means over 400 (!) bytes per position. This seems incredible to me, when in my naive opinion only a few bytes per position would be enough. Is there any explanation for this ?
 
Unfortunately, I can see that the memory allocation in Popeye is done rather clumsily, and this is probably one of the reasons why the program is significantly slower than Alybadix or Gustav.
For the case of up to five pieces, Alybadix has implemented a "quick tree", where a 1:1 positions mapping is used and where 1 GB of RAM is sufficient for problems with five pieces. No hash collision can occur in such case. For expamle, if there are 4 pieces, address for position {a1,a2,a3,a4} is base + a1 + 64*a2 + 64^2*a3 + 64^3*a4, etc.
 
For the previous problem hs==30, about 10 GB of RAM would be enough. Unfortunately, due to the DOS concept, the program cannot address that much memory. In Popeye, however, this would be possible without any problems.
 
Would you consider a similar improvement for problems up to 6 pieces (when there is enough memory available) ?
This would certainly expand the possbility of testable problems

**Comment by thomas-maeder** [comment]
I have activated some of the debugging instrumentation in the hashing machinery.

When I throw Popeye at the Luce problem with 6 GB, this is what I get when the hash table has to be compressed for the first time:

```
 after compression:
key count: 76831884
fxfArenaSize = 6291456 kB
fxfArenaUsed = 6291455 kB
fxfMAXSIZE   = 2048 B
        Size   MallocCnt   FreeCnt
           8       50370   2918376
          15    76781514  75361318
          24    76831884  78279694
         288           1         0
        2048      202090         0
      Total:   153865859 156559388
   Total kB:     3330050   2961405
```
My conclusions are:
- 24 bytes are allocated for each hash table element
- another 15 bytes is the overhead per element
- the remainder is negligible

This gives ~40 bytes per stored position. With the theoretical number of 632'736'000, this means 25GB for the entire problem.

Now I have to find out why there is such a huge difference between your observations and my numbers.

**Comment by vaclavko** [comment]
Good result - after 90 hours only 29GB of RAM is occupied and faster (first move previously 103 hours, now 88 hours - version 4.90)
![image](https://github.com/thomas-maeder/popeye/assets/91785610/4cf66f86-24af-475a-b6dc-949a5503e437)

**Comment by vaclavko** [comment]
One more question: what happens when the allocated memory is full ? In WinChloe it is possible to select in the settings whether the memory is clear or kept. My experience over the years is that it is better to clear the memory and start again. This is most helpful when the first move in the chess problem is a pawn promotion. How does Popeye do this ? Would it be possible to set this up somewhere ?

**Comment by vaclavko** [comment]
solution finished. Time = 94:39:30 h:m:s
[lucehdp30newtest.txt](https://github.com/thomas-maeder/popeye/files/14979929/lucehdp30newtest.txt)

**Comment by thomas-maeder** [comment]
> One more question: what happens when the allocated memory is full?
The elements that are deemed to prevent the least moves from being played are discarded.
Each time, such a cleanup happens, the threshold is increased a little.

> Would it be possible to set this up somewhere?
I think that it is.

I also think that there might be other possibilities to save the amount of memory per position even further.
